# Generated by Django 6.0.4 on 2026-06-01 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50, verbose_name='Quantidade')),
                ('dosage', models.CharField(max_length=100, verbose_name='Dosagem')),
                ('frequency', models.CharField(max_length=100, verbose_name='Frequência')),
                ('duration', models.CharField(max_length=100, verbose_name='Duração')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.medication', verbose_name='Medicamento')),
            ],
            options={
                'verbose_name': 'Item de Receita',
                'verbose_name_plural': 'Itens de Receita',
            },
        ),
    ]
