# Generated by Django 6.0.4 on 2026-05-31 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    atomic = False  # <-- adicione esta linha


    dependencies = [
        ('cids', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(verbose_name='Data/Hora da Consulta')),
                ('anamnesis', models.TextField(blank=True, verbose_name='Anamnese')),
                ('status', models.CharField(choices=[('AG', 'Agendada'), ('AT', 'Em Atendimento'), ('CO', 'Concluída'), ('CA', 'Cancelada')], default='AG', max_length=2, verbose_name='Status')),
                ('cid', models.ManyToManyField(blank=True, to='cids.cid', verbose_name='CIDs')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consults', to='doctors.doctor', verbose_name='Médico')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consults', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-appointment_date'],
            },
        ),
    ]
