# Generated by Django 6.0.4 on 2026-05-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(verbose_name='Alergias')),
                ('family_history', models.TextField(verbose_name='Histórico Familiar')),
                ('notes', models.CharField(max_length=200, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Histórico Médico',
                'verbose_name_plural': 'Históricos Médicos',
                'ordering': ['id'],
            },
        ),
    ]
