# Generated by Django 6.0.4 on 2026-05-31 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicalhistories', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persons.person')),
                ('emergency_contact', models.CharField(max_length=200, verbose_name='Contato de Emergência')),
                ('health_insurance', models.CharField(max_length=100, verbose_name='Convênio')),
                ('allergies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicalhistories.medicalhistory', verbose_name='Alergias')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['name'],
            },
            bases=('persons.person',),
        ),
    ]
