# Generated by Django 6.0.4 on 2026-06-01 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consults', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=200, verbose_name='Tipo de Exame')),
                ('status', models.CharField(choices=[('SO', 'Solicitado'), ('AT', 'Em Andamento'), ('CO', 'Concluído'), ('CA', 'Cancelado')], default='SO', max_length=2, verbose_name='Status')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='Data de Solicitação')),
                ('consult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='consults.consult', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
                'ordering': ['-request_date'],
            },
        ),
    ]
